from __future__ import annotations

from dehalu.schemas import CoderOutput, NormalizedRequest


class FakeLLMProvider:
    name = "fake"
    model = "fake-deterministic-coder-v1"

    def generate(self, request: NormalizedRequest) -> CoderOutput:
        prompt = request.prompt.lower()
        if "syntax error" in prompt:
            code = "def generated_example(:\n    return 1"
        elif "dangerous" in prompt or "eval" in prompt:
            code = (
                "def generated_example(user_input: str):\n"
                "    return eval(user_input)\n"
            )
        elif request.language == "python":
            code = (
                "import math\n\n"
                "def generated_example(value: float) -> float:\n"
                "    return math.sqrt(value)\n"
            )
        else:
            code = f"// Fake provider placeholder for {request.language}\n"

        return CoderOutput(
            provider=self.name,
            model=self.model,
            language=request.language,
            code=code,
            assumptions=[
                "Generated by deterministic fake provider for local development and tests.",
                f"Language selected as {request.language}.",
            ],
            dependencies=[],
            files_touched=[],
            execution_notes=["No sandbox execution was performed in this iteration."],
        )

    def judge(self, request: NormalizedRequest, output: CoderOutput) -> None:
        raise NotImplementedError("Judge support is deferred to a later backend iteration.")

    def repair(self, request: NormalizedRequest, output: CoderOutput) -> None:
        raise NotImplementedError("Repair support is deferred to a later backend iteration.")

    def healthcheck(self) -> bool:
        return True

