from __future__ import annotations

from time import perf_counter

from dehalu.schemas import (
    CoderOutput,
    CoVeCheckVerdict,
    CoVeClaimCheck,
    CoVeResult,
    ExtractedClaim,
    JudgeFinding,
    JudgeResult,
    JudgeVerdict,
    NormalizedRequest,
    PolicyDecision,
    SandboxResult,
    StaticFinding,
    StaticFindingSeverity,
)
from dehalu.verification.judges import build_cove_result, claim_to_question


UNSAFE_TOKENS = ("eval", "exec", "os.system", "subprocess")


class FakeLLMProvider:
    name = "fake"
    model = "fake-deterministic-coder-v1"

    def generate(self, request: NormalizedRequest) -> CoderOutput:
        prompt = request.prompt.lower()
        if "syntax error" in prompt:
            code = "def generated_example(:\n    return 1"
        elif "dangerous" in prompt or "eval" in prompt:
            code = (
                "def generated_example(user_input: str):\n"
                "    return eval(user_input)\n"
            )
        elif request.language == "python":
            code = (
                "import math\n\n"
                "def generated_example(value: float) -> float:\n"
                "    return math.sqrt(value)\n"
            )
        else:
            code = f"// Fake provider placeholder for {request.language}\n"

        return CoderOutput(
            provider=self.name,
            model=self.model,
            language=request.language,
            code=code,
            assumptions=[
                "Generated by deterministic fake provider for local development and tests.",
                f"Language selected as {request.language}.",
            ],
            dependencies=[],
            files_touched=[],
            execution_notes=["No sandbox execution was performed in this iteration."],
        )

    def judge(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
    ) -> JudgeResult:
        started_at = perf_counter()
        findings: list[JudgeFinding] = []
        code = output.code.strip()

        if not code:
            findings.append(
                JudgeFinding(
                    code="empty_output",
                    message="Coder output did not include code to verify.",
                    severity=StaticFindingSeverity.error,
                )
            )

        if output.language != request.language:
            findings.append(
                JudgeFinding(
                    code="language_mismatch",
                    message=(
                        f"Coder output language '{output.language}' does not match "
                        f"requested language '{request.language}'."
                    ),
                    severity=StaticFindingSeverity.error,
                    metadata={
                        "requested_language": request.language,
                        "output_language": output.language,
                    },
                )
            )

        if request.language == "python" and code.startswith("// Fake provider placeholder"):
            findings.append(
                JudgeFinding(
                    code="python_placeholder",
                    message="Python request received a non-Python placeholder output.",
                    severity=StaticFindingSeverity.error,
                    metadata={"language": request.language},
                )
            )

        matched_tokens = [token for token in UNSAFE_TOKENS if token in output.code]
        findings.extend(
            JudgeFinding(
                code="unsafe_or_unverifiable_construct",
                message=f"Code uses construct requiring stronger verification: {token}.",
                severity=StaticFindingSeverity.warning,
                claim=token,
                metadata={"token": token},
            )
            for token in matched_tokens
        )

        errors = [
            finding
            for finding in findings
            if finding.severity == StaticFindingSeverity.error
        ]
        warnings = [
            finding
            for finding in findings
            if finding.severity == StaticFindingSeverity.warning
        ]
        if errors:
            verdict = JudgeVerdict.fail
            hallucination_score = 0.9
        elif warnings:
            verdict = JudgeVerdict.uncertain
            hallucination_score = 0.55
        else:
            verdict = JudgeVerdict.pass_
            hallucination_score = 0.05

        return JudgeResult(
            verdict=verdict,
            provider=self.name,
            model=self.model,
            duration_ms=round((perf_counter() - started_at) * 1000, 3),
            hallucination_score=hallucination_score,
            findings=findings,
            metrics={
                "claim_count": len(claims),
                "static_finding_count": len(static_findings),
                "sandbox_status": sandbox_result.status.value,
                "unsafe_token_count": len(matched_tokens),
            },
        )

    def cove(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
        judge_result: JudgeResult,
    ) -> CoVeResult:
        started_at = perf_counter()
        checks: list[CoVeClaimCheck] = []
        code = output.code.strip()

        if not code:
            checks.append(
                CoVeClaimCheck(
                    claim="generated output",
                    question="Did the coder return code to verify?",
                    answer="No code was returned.",
                    verdict=CoVeCheckVerdict.unsupported,
                    metadata={"reason": "empty_output"},
                )
            )

        if output.language != request.language:
            checks.append(
                CoVeClaimCheck(
                    claim=f"language={request.language}",
                    question="Does the generated output match the requested language?",
                    answer=(
                        f"Output language '{output.language}' does not match "
                        f"requested language '{request.language}'."
                    ),
                    verdict=CoVeCheckVerdict.unsupported,
                    metadata={
                        "requested_language": request.language,
                        "output_language": output.language,
                    },
                )
            )

        for claim in claims:
            answer, verdict = self._verify_claim(claim, output)
            checks.append(
                CoVeClaimCheck(
                    claim=claim.value,
                    question=claim_to_question(claim),
                    answer=answer,
                    verdict=verdict,
                    metadata={"kind": claim.kind, "source": claim.source},
                )
            )

        result = build_cove_result(
            provider=self.name,
            model=self.model,
            duration_ms=(perf_counter() - started_at) * 1000,
            checks=checks,
        )
        result.metrics.update(
            {
                "claim_count": len(claims),
                "static_finding_count": len(static_findings),
                "sandbox_status": sandbox_result.status.value,
                "judge_verdict": judge_result.verdict.value,
            }
        )
        return result

    def repair(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        policy_decision: PolicyDecision,
        judge_result: JudgeResult,
        cove_result: CoVeResult,
    ) -> CoderOutput:
        prompt = request.prompt.lower()
        if "repair failure" in prompt or "still bad" in prompt or "unrepairable" in prompt:
            return CoderOutput(
                provider=self.name,
                model=self.model,
                language=request.language,
                code=output.code,
                assumptions=output.assumptions,
                dependencies=output.dependencies,
                files_touched=output.files_touched,
                execution_notes=["Deterministic fake repair intentionally returned unchanged code."],
            )

        if request.language == "python":
            repaired = self._clean_python_output(request)
        else:
            repaired = CoderOutput(
                provider=self.name,
                model=self.model,
                language=request.language,
                code=f"// Fake provider placeholder for {request.language}\n",
                assumptions=output.assumptions,
                dependencies=[],
                files_touched=[],
                execution_notes=["Fake repair could not produce non-Python code in this iteration."],
            )
        repaired.execution_notes.append(
            f"Repair triggered from policy state {policy_decision.state.value} "
            f"after judge={judge_result.verdict.value} cove={cove_result.verdict.value}."
        )
        return repaired

    def healthcheck(self) -> bool:
        return True

    def _verify_claim(
        self,
        claim: ExtractedClaim,
        output: CoderOutput,
    ) -> tuple[str, CoVeCheckVerdict]:
        code = output.code
        if any(token in code or token in claim.value for token in UNSAFE_TOKENS):
            return (
                "The claim depends on a construct that needs stronger runtime verification.",
                CoVeCheckVerdict.uncertain,
            )

        if claim.kind == "code":
            verdict = (
                CoVeCheckVerdict.supported
                if claim.value.strip() == code.strip()
                else CoVeCheckVerdict.unsupported
            )
            return ("Code claim matches generated output.", verdict)

        if claim.kind == "assumption":
            verdict = (
                CoVeCheckVerdict.supported
                if claim.value in output.assumptions
                else CoVeCheckVerdict.unsupported
            )
            return ("Assumption appears in structured output metadata.", verdict)

        if claim.kind == "dependency":
            verdict = (
                CoVeCheckVerdict.supported
                if claim.value in output.dependencies or claim.value in code
                else CoVeCheckVerdict.unsupported
            )
            return ("Dependency is reflected in metadata or code.", verdict)

        if claim.kind == "import":
            verdict = (
                CoVeCheckVerdict.supported
                if f"import {claim.value}" in code or f"from {claim.value} import" in code
                else CoVeCheckVerdict.unsupported
            )
            return ("Import presence was checked against the code text.", verdict)

        if claim.kind == "symbol":
            verdict = (
                CoVeCheckVerdict.supported
                if claim.value in code
                else CoVeCheckVerdict.unsupported
            )
            return ("Symbol presence was checked against the code text.", verdict)

        return ("The claim type is not modeled by deterministic fake CoVe heuristics.", CoVeCheckVerdict.uncertain)

    def _clean_python_output(self, request: NormalizedRequest) -> CoderOutput:
        return CoderOutput(
            provider=self.name,
            model=self.model,
            language=request.language,
            code=(
                "import math\n\n"
                "def generated_example(value: float) -> float:\n"
                "    return math.sqrt(value)\n"
            ),
            assumptions=[
                "Generated by deterministic fake provider for local development and tests.",
                f"Language selected as {request.language}.",
            ],
            dependencies=[],
            files_touched=[],
            execution_notes=["Deterministic fake repair returned the clean Python fallback."],
        )
