from __future__ import annotations

import json
from time import perf_counter
from typing import Any

import httpx
from pydantic import BaseModel, Field, ValidationError

from dehalu.adapters.llm.runtime import (
    ProviderExecutionError,
    build_invocation_record,
    classify_provider_failure,
)
from dehalu.core.settings import Settings
from dehalu.orchestration.prompts import (
    PromptRender,
    clarification_prompt,
    cove_prompt,
    generation_prompt,
    judge_prompt,
    repair_prompt,
)
from dehalu.schemas import (
    AgentRole,
    ClarificationResult,
    CoderOutput,
    CoVeClaimCheck,
    CoVeFinding,
    CoVeResult,
    ExtractedClaim,
    JudgeFinding,
    JudgeResult,
    JudgeVerdict,
    NormalizedRequest,
    PolicyDecision,
    ProviderFailureKind,
    SandboxResult,
    StaticFinding,
    StaticFindingSeverity,
)
from dehalu.verification.judges import build_cove_result


class GeminiJudgePayload(BaseModel):
    verdict: JudgeVerdict
    hallucination_score: float = Field(ge=0.0, le=1.0)
    findings: list[JudgeFinding] = Field(default_factory=list)
    metrics: dict[str, Any] = Field(default_factory=dict)


class GeminiCoVePayload(BaseModel):
    checks: list[CoVeClaimCheck] = Field(default_factory=list)
    findings: list[CoVeFinding] = Field(default_factory=list)
    hallucination_score: float | None = Field(default=None, ge=0.0, le=1.0)


class GeminiLLMProvider:
    name = "gemini"

    def __init__(
        self,
        settings: Settings,
        http_client: httpx.Client | None = None,
    ) -> None:
        self.api_key = settings.gemini_api_key
        self.base_url = settings.gemini_base_url.rstrip("/")
        self.generate_model = settings.gemini_generate_model
        self.verify_model = settings.gemini_verify_model
        self.timeout_seconds = settings.gemini_timeout_seconds
        self.retry_attempts = settings.gemini_retry_attempts
        self.prompt_policy_version = settings.prompt_policy_version
        self.routing_policy_version = settings.routing_policy_version
        self.capture_full_payloads = settings.provider_capture_full_payloads
        self.smoke_checks_enabled = settings.provider_live_smoke_checks_enabled
        self._client = http_client or httpx.Client(timeout=self.timeout_seconds)

    def generate(self, request: NormalizedRequest) -> CoderOutput:
        render = generation_prompt(self.name, request)
        body, text, invocation = self._generate_content(
            model=self.generate_model,
            render=render,
            role=AgentRole.coder,
            generation_config={"temperature": 0.1, "maxOutputTokens": 2048},
        )
        return CoderOutput(
            provider=self.name,
            model=self.generate_model,
            language=request.language,
            code=self._strip_code_fences(text),
            assumptions=[
                "Generated by Gemini through the backend provider adapter.",
                f"Language selected as {request.language}.",
            ],
            dependencies=[],
            files_touched=[],
            execution_notes=["No runtime execution was performed in this iteration."],
            metadata=self._metadata(invocation, body),
        )

    def clarify(self, request: NormalizedRequest) -> ClarificationResult:
        render = clarification_prompt(self.name, request)
        try:
            body, text, invocation = self._generate_content(
                model=self.verify_model,
                render=render,
                role=AgentRole.clarifier,
                generation_config={"temperature": 0.0, "responseMimeType": "application/json"},
            )
            payload = json.loads(text)
            return ClarificationResult(
                clarified_prompt=request.prompt,
                requested_outcome=payload.get("requested_outcome", request.prompt),
                language=payload.get("language", request.language),
                runtime_assumptions=payload.get("runtime_assumptions", []),
                constraints=payload.get("constraints", []),
                acceptance_criteria=payload.get("acceptance_criteria", request.acceptance_criteria),
                ambiguity_flags=payload.get("ambiguity_flags", []),
                needs_user_input=payload.get("needs_user_input", False),
                confidence=payload.get("confidence", 0.5),
                metadata=self._metadata(invocation, body),
            )
        except ProviderExecutionError as exc:
            return self._clarification_fallback(request, exc.record)
        except (ValueError, json.JSONDecodeError) as exc:
            failure_kind, _ = classify_provider_failure(exc)
            record = build_invocation_record(
                provider_name=self.name,
                model=self.verify_model,
                stage="clarification",
                role=AgentRole.clarifier,
                started_at=perf_counter(),
                retry_count=0,
                prompt_template_version=render.version,
                routing_policy_version=self.routing_policy_version,
                success=False,
                failure_kind=failure_kind,
                metadata={"error_type": type(exc).__name__, "parse_failure": True},
            )
            return self._clarification_fallback(request, record)

    def judge(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
    ) -> JudgeResult:
        render = judge_prompt(self.name, request, output, claims, static_findings, sandbox_result)
        try:
            _, text, invocation = self._generate_content(
                model=self.verify_model,
                render=render,
                role=AgentRole.judge,
                generation_config={
                    "temperature": 0.0,
                    "responseMimeType": "application/json",
                    "responseJsonSchema": GeminiJudgePayload.model_json_schema(),
                },
            )
            payload = GeminiJudgePayload.model_validate_json(text)
            return JudgeResult(
                verdict=payload.verdict,
                provider=self.name,
                model=self.verify_model,
                duration_ms=invocation.latency_ms,
                hallucination_score=payload.hallucination_score,
                findings=payload.findings,
                metrics={
                    **payload.metrics,
                    "claim_count": len(claims),
                    "static_finding_count": len(static_findings),
                    "sandbox_status": sandbox_result.status.value,
                    "provider_invocation": invocation.model_dump(mode="json"),
                },
            )
        except ProviderExecutionError as exc:
            return self._judge_fallback(claims, static_findings, sandbox_result, exc.record, exc)
        except (ValidationError, ValueError) as exc:
            failure_kind, _ = classify_provider_failure(exc)
            record = build_invocation_record(
                provider_name=self.name,
                model=self.verify_model,
                stage="judge",
                role=AgentRole.judge,
                started_at=perf_counter(),
                retry_count=0,
                prompt_template_version=render.version,
                routing_policy_version=self.routing_policy_version,
                success=False,
                failure_kind=failure_kind,
                metadata={"error_type": type(exc).__name__, "parse_failure": True},
            )
            return self._judge_fallback(claims, static_findings, sandbox_result, record, exc)

    def cove(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
        judge_result: JudgeResult,
    ) -> CoVeResult:
        render = cove_prompt(self.name, request, output, claims, static_findings, sandbox_result, judge_result)
        try:
            _, text, invocation = self._generate_content(
                model=self.verify_model,
                render=render,
                role=AgentRole.cove,
                generation_config={
                    "temperature": 0.0,
                    "responseMimeType": "application/json",
                    "responseJsonSchema": GeminiCoVePayload.model_json_schema(),
                },
            )
            payload = GeminiCoVePayload.model_validate_json(text)
            result = build_cove_result(
                provider=self.name,
                model=self.verify_model,
                duration_ms=invocation.latency_ms,
                checks=payload.checks,
                extra_findings=payload.findings,
                hallucination_score=payload.hallucination_score,
            )
            result.metrics.update(
                {
                    "claim_count": len(claims),
                    "static_finding_count": len(static_findings),
                    "sandbox_status": sandbox_result.status.value,
                    "judge_verdict": judge_result.verdict.value,
                    "provider_invocation": invocation.model_dump(mode="json"),
                }
            )
            return result
        except ProviderExecutionError as exc:
            return self._cove_fallback(claims, static_findings, sandbox_result, judge_result, exc.record, exc)
        except (ValidationError, ValueError) as exc:
            failure_kind, _ = classify_provider_failure(exc)
            record = build_invocation_record(
                provider_name=self.name,
                model=self.verify_model,
                stage="cove",
                role=AgentRole.cove,
                started_at=perf_counter(),
                retry_count=0,
                prompt_template_version=render.version,
                routing_policy_version=self.routing_policy_version,
                success=False,
                failure_kind=failure_kind,
                metadata={"error_type": type(exc).__name__, "parse_failure": True},
            )
            return self._cove_fallback(claims, static_findings, sandbox_result, judge_result, record, exc)

    def repair(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        policy_decision: PolicyDecision,
        judge_result: JudgeResult,
        cove_result: CoVeResult,
    ) -> CoderOutput:
        render = repair_prompt(self.name, request, output, policy_decision, judge_result, cove_result)
        try:
            body, text, invocation = self._generate_content(
                model=self.verify_model,
                render=render,
                role=AgentRole.repair,
                generation_config={"temperature": 0.0, "maxOutputTokens": 2048},
            )
            code = self._strip_code_fences(text)
            if not code.strip():
                raise ValueError("Gemini repair output was empty.")
            return CoderOutput(
                provider=self.name,
                model=self.verify_model,
                language=request.language,
                code=code,
                assumptions=[
                    "Generated by Gemini repair flow through the backend provider adapter.",
                    f"Language selected as {request.language}.",
                ],
                dependencies=[],
                files_touched=[],
                execution_notes=["Gemini repair returned revised code for re-verification."],
                metadata=self._metadata(invocation, body),
            )
        except ProviderExecutionError as exc:
            return self._repair_fallback(request, exc.record, f"Gemini repair failed: {exc}")
        except ValueError as exc:
            failure_kind, _ = classify_provider_failure(exc)
            record = build_invocation_record(
                provider_name=self.name,
                model=self.verify_model,
                stage="repair",
                role=AgentRole.repair,
                started_at=perf_counter(),
                retry_count=0,
                prompt_template_version=render.version,
                routing_policy_version=self.routing_policy_version,
                success=False,
                failure_kind=failure_kind,
                metadata={"error_type": type(exc).__name__},
            )
            return self._repair_fallback(request, record, f"Gemini repair failed: {exc}")

    def healthcheck(self) -> bool:
        return bool(self.api_key)

    def health_details(self) -> dict[str, Any]:
        live_status = "skipped"
        if self.smoke_checks_enabled and self.api_key:
            try:
                self._generate_content(
                    model=self.verify_model,
                    render=PromptRender(
                        system_instruction="Reply with OK.",
                        prompt="OK",
                        version=self.prompt_policy_version,
                        role="smokecheck",
                        provider_name=self.name,
                    ),
                    role=AgentRole.judge,
                    generation_config={"temperature": 0.0, "maxOutputTokens": 8},
                )
                live_status = "passed"
            except Exception:
                live_status = "failed"
        return {
            "configured": bool(self.api_key),
            "api_key_present": bool(self.api_key),
            "smoke_check_enabled": self.smoke_checks_enabled,
            "live_smoke_check": live_status,
            "models": {
                "generate": self.generate_model,
                "verify": self.verify_model,
            },
            "retry_attempts": self.retry_attempts,
        }

    def _generate_content(
        self,
        *,
        model: str,
        render: PromptRender,
        role: AgentRole,
        generation_config: dict[str, Any] | None = None,
    ) -> tuple[dict[str, Any], str, Any]:
        if not self.api_key:
            record = build_invocation_record(
                provider_name=self.name,
                model=model,
                stage=render.role,
                role=role,
                started_at=perf_counter(),
                retry_count=0,
                prompt_template_version=render.version,
                routing_policy_version=self.routing_policy_version,
                success=False,
                failure_kind=ProviderFailureKind.misconfiguration,
                metadata={"error_type": "MissingAPIKey"},
            )
            raise ProviderExecutionError("Gemini provider is not configured.", record=record)

        payload: dict[str, Any] = {
            "systemInstruction": {"parts": [{"text": render.system_instruction}]},
            "contents": [{"parts": [{"text": render.prompt}]}],
        }
        if generation_config:
            payload["generationConfig"] = generation_config

        started_at = perf_counter()
        retry_count = 0
        while True:
            try:
                response = self._client.post(
                    f"{self.base_url}/models/{model}:generateContent",
                    headers={"x-goog-api-key": self.api_key, "Content-Type": "application/json"},
                    json=payload,
                )
                response.raise_for_status()
                body = response.json()
                text = self._extract_text(body)
                record = build_invocation_record(
                    provider_name=self.name,
                    model=model,
                    stage=render.role,
                    role=role,
                    started_at=started_at,
                    retry_count=retry_count,
                    prompt_template_version=render.version,
                    routing_policy_version=self.routing_policy_version,
                    success=True,
                    usage=body.get("usageMetadata", {}),
                    request_summary={"model": model, "generation_config": generation_config or {}},
                    response_summary=self._response_summary(body, text),
                    metadata={"http_status": response.status_code},
                )
                return body, text, record
            except Exception as exc:
                failure_kind, retryable = classify_provider_failure(exc if isinstance(exc, Exception) else Exception())
                if retryable and retry_count < self.retry_attempts:
                    retry_count += 1
                    continue
                record = build_invocation_record(
                    provider_name=self.name,
                    model=model,
                    stage=render.role,
                    role=role,
                    started_at=started_at,
                    retry_count=retry_count,
                    prompt_template_version=render.version,
                    routing_policy_version=self.routing_policy_version,
                    success=False,
                    failure_kind=failure_kind,
                    request_summary={"model": model, "generation_config": generation_config or {}},
                    response_summary={},
                    metadata={"error_type": type(exc).__name__, "message": str(exc)},
                )
                raise ProviderExecutionError(str(exc), record=record) from exc

    def _metadata(self, invocation, body: dict[str, Any]) -> dict[str, Any]:
        metadata = {
            "provider": self.name,
            "prompt_template_version": invocation.prompt_template_version,
            "routing_policy_version": invocation.routing_policy_version,
            "provider_invocation": invocation.model_dump(mode="json"),
        }
        if self.capture_full_payloads:
            metadata["raw_response"] = body
        return metadata

    def _clarification_fallback(self, request: NormalizedRequest, invocation) -> ClarificationResult:
        return ClarificationResult(
            clarified_prompt=request.prompt,
            requested_outcome=request.prompt,
            language=request.language,
            runtime_assumptions=[],
            constraints=[],
            acceptance_criteria=request.acceptance_criteria,
            ambiguity_flags=[],
            needs_user_input=False,
            confidence=0.35,
            metadata={
                "provider": self.name,
                "model": self.verify_model,
                "fallback": True,
                "provider_invocation": invocation.model_dump(mode="json"),
            },
        )

    def _judge_fallback(self, claims, static_findings, sandbox_result, invocation, exc: Exception) -> JudgeResult:
        return JudgeResult(
            verdict=JudgeVerdict.uncertain,
            provider=self.name,
            model=self.verify_model,
            duration_ms=invocation.latency_ms,
            hallucination_score=0.6,
            findings=[
                JudgeFinding(
                    code="judge_provider_error",
                    message=f"Gemini judge output could not be validated: {exc}",
                    severity=StaticFindingSeverity.warning,
                    metadata={"error_type": type(exc).__name__},
                )
            ],
            metrics={
                "claim_count": len(claims),
                "static_finding_count": len(static_findings),
                "sandbox_status": sandbox_result.status.value,
                "provider_error": type(exc).__name__,
                "provider_invocation": invocation.model_dump(mode="json"),
            },
        )

    def _cove_fallback(self, claims, static_findings, sandbox_result, judge_result, invocation, exc: Exception) -> CoVeResult:
        result = build_cove_result(
            provider=self.name,
            model=self.verify_model,
            duration_ms=invocation.latency_ms,
            checks=[],
            extra_findings=[
                CoVeFinding(
                    code="cove_provider_error",
                    message=f"Gemini CoVe output could not be validated: {exc}",
                    severity=StaticFindingSeverity.warning,
                    metadata={"error_type": type(exc).__name__},
                )
            ],
            hallucination_score=0.6,
        )
        result.metrics.update(
            {
                "claim_count": len(claims),
                "static_finding_count": len(static_findings),
                "sandbox_status": sandbox_result.status.value,
                "judge_verdict": judge_result.verdict.value,
                "provider_error": type(exc).__name__,
                "provider_invocation": invocation.model_dump(mode="json"),
            }
        )
        return result

    def _repair_fallback(self, request: NormalizedRequest, invocation, note: str) -> CoderOutput:
        return CoderOutput(
            provider=self.name,
            model=self.verify_model,
            language=request.language,
            code="",
            assumptions=[
                "Gemini repair did not return a valid replacement output.",
                f"Language selected as {request.language}.",
            ],
            dependencies=[],
            files_touched=[],
            execution_notes=[note],
            metadata={"provider": self.name, "provider_invocation": invocation.model_dump(mode="json")},
        )

    def _extract_text(self, response_body: dict[str, Any]) -> str:
        candidates = response_body.get("candidates", [])
        if not candidates:
            raise ValueError("Gemini response did not contain candidates.")
        parts = candidates[0].get("content", {}).get("parts", [])
        texts = [part.get("text", "") for part in parts if part.get("text")]
        text = "".join(texts).strip()
        if not text:
            raise ValueError("Gemini response did not contain text parts.")
        return text

    def _response_summary(self, body: dict[str, Any], text: str) -> dict[str, Any]:
        summary = {
            "candidate_count": len(body.get("candidates", [])),
            "text_length": len(text),
        }
        if body.get("usageMetadata"):
            summary["usage"] = body["usageMetadata"]
        if self.capture_full_payloads:
            summary["raw_response"] = body
        return summary

    def _strip_code_fences(self, text: str) -> str:
        stripped = text.strip()
        if "```" not in stripped:
            return stripped
        lines = stripped.splitlines()
        in_fence = False
        fenced: list[str] = []
        for line in lines:
            if line.strip().startswith("```"):
                if in_fence:
                    break
                in_fence = True
                continue
            if in_fence:
                fenced.append(line)
        return "\n".join(fenced).strip() or stripped.replace("```", "").strip()
