from __future__ import annotations

import json
from time import perf_counter
from typing import Any

import httpx
from pydantic import BaseModel, Field, ValidationError

from dehalu.core.settings import Settings
from dehalu.schemas import (
    ClarificationResult,
    CoderOutput,
    CoVeClaimCheck,
    CoVeFinding,
    CoVeResult,
    ExtractedClaim,
    JudgeFinding,
    JudgeResult,
    JudgeVerdict,
    NormalizedRequest,
    PolicyDecision,
    SandboxResult,
    StaticFinding,
    StaticFindingSeverity,
)
from dehalu.verification.judges import build_cove_result


class GeminiJudgePayload(BaseModel):
    verdict: JudgeVerdict
    hallucination_score: float = Field(ge=0.0, le=1.0)
    findings: list[JudgeFinding] = Field(default_factory=list)
    metrics: dict[str, Any] = Field(default_factory=dict)


class GeminiCoVePayload(BaseModel):
    checks: list[CoVeClaimCheck] = Field(default_factory=list)
    findings: list[CoVeFinding] = Field(default_factory=list)
    hallucination_score: float | None = Field(default=None, ge=0.0, le=1.0)


class GeminiLLMProvider:
    name = "gemini"

    def __init__(
        self,
        settings: Settings,
        http_client: httpx.Client | None = None,
    ) -> None:
        self.api_key = settings.gemini_api_key
        self.base_url = settings.gemini_base_url.rstrip("/")
        self.generate_model = settings.gemini_generate_model
        self.verify_model = settings.gemini_verify_model
        self.timeout_seconds = settings.gemini_timeout_seconds
        self._client = http_client or httpx.Client(timeout=self.timeout_seconds)

    def generate(self, request: NormalizedRequest) -> CoderOutput:
        prompt = (
            "Return only source code.\n"
            f"Requested language: {request.language}\n"
            f"Risk level: {request.risk_level.value}\n"
            f"Latency budget seconds: {request.latency_budget_seconds}\n"
            f"User prompt:\n{request.prompt}\n"
        )
        response = self._generate_content(
            model=self.generate_model,
            system_instruction=(
                "You are a coding model inside a verification gateway. "
                "Return only the requested source code without markdown fences."
            ),
            prompt=prompt,
            generation_config={"temperature": 0.1, "maxOutputTokens": 2048},
        )
        code = self._strip_code_fences(self._extract_text(response))
        return CoderOutput(
            provider=self.name,
            model=self.generate_model,
            language=request.language,
            code=code,
            assumptions=[
                "Generated by Gemini through the synchronous backend provider adapter.",
                f"Language selected as {request.language}.",
            ],
            dependencies=[],
            files_touched=[],
            execution_notes=["No runtime execution was performed in this iteration."],
        )

    def clarify(self, request: NormalizedRequest) -> ClarificationResult:
        prompt = (
            "Normalize the coding request into a structured task spec.\n"
            "Return strict JSON with requested_outcome, language, runtime_assumptions, "
            "constraints, acceptance_criteria, ambiguity_flags, needs_user_input, confidence.\n"
            f"Request:\n{request.model_dump_json(indent=2)}\n"
        )
        try:
            response = self._generate_content(
                model=self.verify_model,
                system_instruction="You clarify software requests before generation. Return strict JSON only.",
                prompt=prompt,
                generation_config={"temperature": 0.0, "responseMimeType": "application/json"},
            )
            payload = json.loads(self._extract_text(response))
            return ClarificationResult(
                clarified_prompt=request.prompt,
                requested_outcome=payload.get("requested_outcome", request.prompt),
                language=payload.get("language", request.language),
                runtime_assumptions=payload.get("runtime_assumptions", []),
                constraints=payload.get("constraints", []),
                acceptance_criteria=payload.get("acceptance_criteria", request.acceptance_criteria),
                ambiguity_flags=payload.get("ambiguity_flags", []),
                needs_user_input=payload.get("needs_user_input", False),
                confidence=payload.get("confidence", 0.5),
                metadata={"provider": self.name, "model": self.verify_model},
            )
        except (ValueError, httpx.HTTPError, json.JSONDecodeError):
            return ClarificationResult(
                clarified_prompt=request.prompt,
                requested_outcome=request.prompt,
                language=request.language,
                runtime_assumptions=[],
                constraints=[],
                acceptance_criteria=request.acceptance_criteria,
                ambiguity_flags=[],
                needs_user_input=False,
                confidence=0.35,
                metadata={"provider": self.name, "model": self.verify_model, "fallback": True},
            )

    def judge(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
    ) -> JudgeResult:
        started_at = perf_counter()
        try:
            response = self._generate_content(
                model=self.verify_model,
                system_instruction=(
                    "You are a code hallucination judge. "
                    "Return strict JSON that matches the requested schema."
                ),
                prompt=self._build_judge_prompt(
                    request,
                    output,
                    claims,
                    static_findings,
                    sandbox_result,
                ),
                generation_config={
                    "temperature": 0.0,
                    "responseMimeType": "application/json",
                    "responseJsonSchema": GeminiJudgePayload.model_json_schema(),
                },
            )
            payload = GeminiJudgePayload.model_validate_json(self._extract_text(response))
            metrics = {
                **payload.metrics,
                "claim_count": len(claims),
                "static_finding_count": len(static_findings),
                "sandbox_status": sandbox_result.status.value,
            }
            return JudgeResult(
                verdict=payload.verdict,
                provider=self.name,
                model=self.verify_model,
                duration_ms=round((perf_counter() - started_at) * 1000, 3),
                hallucination_score=payload.hallucination_score,
                findings=payload.findings,
                metrics=metrics,
            )
        except (ValidationError, ValueError, httpx.HTTPError) as exc:
            return JudgeResult(
                verdict=JudgeVerdict.uncertain,
                provider=self.name,
                model=self.verify_model,
                duration_ms=round((perf_counter() - started_at) * 1000, 3),
                hallucination_score=0.6,
                findings=[
                    JudgeFinding(
                        code="judge_provider_error",
                        message=f"Gemini judge output could not be validated: {exc}",
                        severity=StaticFindingSeverity.warning,
                        metadata={"error_type": type(exc).__name__},
                    )
                ],
                metrics={
                    "claim_count": len(claims),
                    "static_finding_count": len(static_findings),
                    "sandbox_status": sandbox_result.status.value,
                    "provider_error": type(exc).__name__,
                },
            )

    def cove(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
        judge_result: JudgeResult,
    ) -> CoVeResult:
        started_at = perf_counter()
        try:
            response = self._generate_content(
                model=self.verify_model,
                system_instruction=(
                    "You are a Chain-of-Verification checker for generated code. "
                    "Return strict JSON that matches the requested schema."
                ),
                prompt=self._build_cove_prompt(
                    request,
                    output,
                    claims,
                    static_findings,
                    sandbox_result,
                    judge_result,
                ),
                generation_config={
                    "temperature": 0.0,
                    "responseMimeType": "application/json",
                    "responseJsonSchema": GeminiCoVePayload.model_json_schema(),
                },
            )
            payload = GeminiCoVePayload.model_validate_json(self._extract_text(response))
            result = build_cove_result(
                provider=self.name,
                model=self.verify_model,
                duration_ms=(perf_counter() - started_at) * 1000,
                checks=payload.checks,
                extra_findings=payload.findings,
                hallucination_score=payload.hallucination_score,
            )
            result.metrics.update(
                {
                    "claim_count": len(claims),
                    "static_finding_count": len(static_findings),
                    "sandbox_status": sandbox_result.status.value,
                    "judge_verdict": judge_result.verdict.value,
                }
            )
            return result
        except (ValidationError, ValueError, httpx.HTTPError) as exc:
            result = build_cove_result(
                provider=self.name,
                model=self.verify_model,
                duration_ms=(perf_counter() - started_at) * 1000,
                checks=[],
                extra_findings=[
                    CoVeFinding(
                        code="cove_provider_error",
                        message=f"Gemini CoVe output could not be validated: {exc}",
                        severity=StaticFindingSeverity.warning,
                        metadata={"error_type": type(exc).__name__},
                    )
                ],
                hallucination_score=0.6,
            )
            result.metrics.update(
                {
                    "claim_count": len(claims),
                    "static_finding_count": len(static_findings),
                    "sandbox_status": sandbox_result.status.value,
                    "judge_verdict": judge_result.verdict.value,
                    "provider_error": type(exc).__name__,
                }
            )
            return result

    def repair(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        policy_decision: PolicyDecision,
        judge_result: JudgeResult,
        cove_result: CoVeResult,
    ) -> CoderOutput:
        try:
            response = self._generate_content(
                model=self.verify_model,
                system_instruction=(
                    "You repair generated source code after hallucination detection. "
                    "Return only revised source code without markdown fences."
                ),
                prompt=self._build_repair_prompt(
                    request,
                    output,
                    policy_decision,
                    judge_result,
                    cove_result,
                ),
                generation_config={"temperature": 0.0, "maxOutputTokens": 2048},
            )
            code = self._strip_code_fences(self._extract_text(response))
            if not code.strip():
                raise ValueError("Gemini repair output was empty.")
            return CoderOutput(
                provider=self.name,
                model=self.verify_model,
                language=request.language,
                code=code,
                assumptions=[
                    "Generated by Gemini repair flow through the synchronous backend provider adapter.",
                    f"Language selected as {request.language}.",
                ],
                dependencies=[],
                files_touched=[],
                execution_notes=["Gemini repair returned revised code for re-verification."],
            )
        except (ValueError, httpx.HTTPError) as exc:
            return CoderOutput(
                provider=self.name,
                model=self.verify_model,
                language=request.language,
                code="",
                assumptions=[
                    "Gemini repair did not return a valid replacement output.",
                    f"Language selected as {request.language}.",
                ],
                dependencies=[],
                files_touched=[],
                execution_notes=[f"Gemini repair failed: {exc}"],
            )

    def healthcheck(self) -> bool:
        return bool(self.api_key)

    def _build_judge_prompt(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
    ) -> str:
        return (
            "Evaluate whether the generated code is hallucinated or unsupported.\n"
            "Use only the evidence below.\n\n"
            f"Normalized request:\n{request.model_dump_json(indent=2)}\n\n"
            f"Coder output:\n{output.model_dump_json(indent=2)}\n\n"
            f"Extracted claims:\n{self._dump_models(claims)}\n\n"
            f"Static findings:\n{self._dump_models(static_findings)}\n\n"
            f"Sandbox result:\n{sandbox_result.model_dump_json(indent=2)}\n"
        )

    def _build_cove_prompt(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        claims: list[ExtractedClaim],
        static_findings: list[StaticFinding],
        sandbox_result: SandboxResult,
        judge_result: JudgeResult,
    ) -> str:
        return (
            "Re-check each extracted claim independently against the generated code.\n"
            "Return one structured check per claim and summarize unsupported or uncertain claims.\n\n"
            f"Normalized request:\n{request.model_dump_json(indent=2)}\n\n"
            f"Coder output:\n{output.model_dump_json(indent=2)}\n\n"
            f"Extracted claims:\n{self._dump_models(claims)}\n\n"
            f"Static findings:\n{self._dump_models(static_findings)}\n\n"
            f"Sandbox result:\n{sandbox_result.model_dump_json(indent=2)}\n\n"
            f"Judge result:\n{judge_result.model_dump_json(indent=2)}\n"
        )

    def _build_repair_prompt(
        self,
        request: NormalizedRequest,
        output: CoderOutput,
        policy_decision: PolicyDecision,
        judge_result: JudgeResult,
        cove_result: CoVeResult,
    ) -> str:
        return (
            "Revise the generated code to address hallucination or unsupported-claim findings.\n"
            "Return only corrected source code.\n\n"
            f"Normalized request:\n{request.model_dump_json(indent=2)}\n\n"
            f"Current coder output:\n{output.model_dump_json(indent=2)}\n\n"
            f"Policy decision:\n{policy_decision.model_dump_json(indent=2)}\n\n"
            f"Judge result:\n{judge_result.model_dump_json(indent=2)}\n\n"
            f"CoVe result:\n{cove_result.model_dump_json(indent=2)}\n"
        )

    def _generate_content(
        self,
        *,
        model: str,
        system_instruction: str,
        prompt: str,
        generation_config: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if not self.api_key:
            raise ValueError("Gemini provider is not configured. Set DEHALU_GEMINI_API_KEY.")

        payload: dict[str, Any] = {
            "systemInstruction": {"parts": [{"text": system_instruction}]},
            "contents": [{"parts": [{"text": prompt}]}],
        }
        if generation_config:
            payload["generationConfig"] = generation_config

        response = self._client.post(
            f"{self.base_url}/models/{model}:generateContent",
            headers={"x-goog-api-key": self.api_key, "Content-Type": "application/json"},
            json=payload,
        )
        response.raise_for_status()
        return response.json()

    def _extract_text(self, response_body: dict[str, Any]) -> str:
        candidates = response_body.get("candidates", [])
        if not candidates:
            raise ValueError("Gemini response did not contain candidates.")

        parts = candidates[0].get("content", {}).get("parts", [])
        texts = [part.get("text", "") for part in parts if part.get("text")]
        text = "".join(texts).strip()
        if not text:
            raise ValueError("Gemini response did not contain text parts.")
        return text

    def _strip_code_fences(self, text: str) -> str:
        stripped = text.strip()
        if not stripped.startswith("```"):
            return stripped
        lines = stripped.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        return "\n".join(lines).strip()

    def _dump_models(self, models: list[BaseModel]) -> str:
        if not models:
            return "[]"
        return "[\n" + ",\n".join(model.model_dump_json(indent=2) for model in models) + "\n]"
