"""Generate client domain types from the same schemas exposed through OpenAPI."""
import json
from pathlib import Path
from dehalu.main import create_app
from dehalu.domain.models import RunEvent
root = Path(__file__).resolve().parents[2]
spec = create_app().openapi()
schemas = spec['components']['schemas']
schemas['RunEvent'] = RunEvent.model_json_schema()

def ts(schema):
    if '$ref' in schema: return schema['$ref'].split('/')[-1]
    if 'enum' in schema: return ' | '.join(json.dumps(v) for v in schema['enum'])
    if 'const' in schema: return json.dumps(schema['const'])
    if 'anyOf' in schema: return ' | '.join(ts(s) for s in schema['anyOf'])
    kind = schema.get('type')
    if kind == 'null': return 'null'
    if kind in {'number', 'integer'}: return 'number'
    if kind == 'boolean': return 'boolean'
    if kind == 'string': return 'string'
    if kind == 'array': return f"Array<{ts(schema['items'])}>"
    if kind == 'object':
        if 'properties' not in schema:
            additional = schema.get('additionalProperties', {})
            return f'Record<string, {ts(additional) if isinstance(additional, dict) else "unknown"}>'
        return '{\n' + '\n'.join(f'  {name}{"?" if name not in schema.get("required", []) and schema.get("title") in {"RunCreate", "ClarificationAnswers"} else ""}: {ts(value)};' for name, value in schema['properties'].items()) + '\n}'
    return 'unknown'

output = '// Generated by backend/scripts/generate_contracts.py; do not edit.\n'
for name, schema in sorted(schemas.items()): output += f'export type {name} = {ts(schema)};\n\n'
(root / 'frontend/lib/contracts.generated.ts').write_text(output)
