// Generated by backend/scripts/generate_contracts.py; do not edit.
export type AnalyzerCoverage = {
  analyzer: string;
  language: string;
  status: "available" | "partial" | "unavailable" | "failed";
  detail: string;
  version: string | null;
};

export type AttemptEvidence = {
  output: GeneratedOutput;
  claims: Array<Claim>;
  static_findings: Array<StaticFinding>;
  coverage: Array<AnalyzerCoverage>;
  metrics: MetricResult;
  judge_results: Array<JudgeResult>;
  judge_consensus: JudgeConsensus;
  cove_results: Array<CoVeResult>;
  policy: PolicyDecision;
};

export type Claim = {
  id: string;
  claim_type: string;
  claim_text: string;
  location: string;
  status: "not_checked" | "supported" | "unsupported" | "uncertain";
  source_range: Record<string, number>;
  check_method: string;
  evidence_ids: Array<string>;
  evidence: string;
  details: Record<string, unknown>;
};

export type ClarificationAnswers = {
  answers: string;
  language_hint?: string | null;
};

export type CoVeResult = {
  claim_id: string | null;
  verification_question: string;
  verdict: "supported" | "unsupported" | "uncertain";
  evidence: string;
  evidence_ids: Array<string>;
  confidence: number;
};

export type GeneratedOutput = {
  id: string;
  attempt_no: number;
  code: string;
  explanation: string;
  provider: string;
  entropy_summary: Record<string, unknown>;
  logprob_summary: Record<string, unknown>;
  metadata: Record<string, unknown>;
  repair_summary: Array<string>;
};

export type HTTPValidationError = {
  detail: Array<ValidationError>;
};

export type HealthResponse = {
  status: string;
  database: string;
  ollama: Record<string, unknown>;
  judges: Record<string, unknown>;
  capabilities: Array<AnalyzerCoverage>;
};

export type InferenceResult = {
  language: string | null;
  framework: string | null;
  runtime: string | null;
  libraries: Array<string>;
  requirements: Array<string>;
  constraints: Array<string>;
  uncertain_assumptions: Array<string>;
  clarification_questions: Array<string>;
  needs_clarification: boolean;
};

export type JudgeConsensus = {
  final_verdict: "pass" | "warn" | "fail";
  average_score: number | null;
  agreement_level: string;
  summary: string;
  valid_count: number;
  expected_count: number;
};

export type JudgeResult = {
  judge_name: string;
  judge_model: string;
  role: string;
  status: "ok" | "unavailable" | "failed" | "simulated";
  verdict: "pass" | "warn" | "fail" | null;
  score: number | null;
  rubric_json: Record<string, unknown>;
  explanation: string;
  blocking_issues: Array<string>;
  evidence_ids: Array<string>;
  repair_suggestions: Array<string>;
};

export type MetricResult = {
  mihn: number;
  mahr: number;
  tr_s: number;
  entropy_score: number | null;
  hallucination_risk_score: number;
  static_severity_score: number;
  uncertainty_score: number;
  unsupported_count: number;
  uncertain_count: number;
  total_claims: number;
  version: string;
};

export type PolicyDecision = {
  decision: "accept" | "warn" | "repair" | "reject" | "needs_clarification";
  reason: string;
  evidence_ids: Array<string>;
  version: string;
};

export type RunCreate = {
  prompt: string;
  language_hint?: string | null;
  framework_hint?: string | null;
  runtime_hint?: string | null;
  libraries?: Array<string>;
  max_retry?: number | null;
  constraints?: Array<string>;
};

export type RunEvent = {
  run_id: string;
  sequence: number;
  timestamp: string;
  type: string;
  payload: Record<string, unknown>;
};

export type RunEvidence = {
  run: RunSummary;
  attempts: Array<AttemptEvidence>;
  partial: Record<string, unknown>;
};

export type RunSummary = {
  id: string;
  status: string;
  prompt: string;
  inferred: InferenceResult;
  model_name: string;
  max_retry: number;
  created_at: string | null;
  completed_at: string | null;
  error: string | null;
  final_output: GeneratedOutput | null;
  policy_decision: PolicyDecision | null;
};

export type StaticFinding = {
  id: string;
  rule_id: string;
  severity: "info" | "warning" | "error";
  message: string;
  location: string;
  evidence_source: string;
  claim_ids: Array<string>;
  source_range: Record<string, number>;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input: unknown;
  ctx: Record<string, unknown>;
};

