/**
 * Export & Report Generation
 * Generate reports in JSON, CSV, and PDF formats
 */

export interface RunReport {
  runId: string;
  timestamp: string;
  prompt: string;
  language: string;
  status: string;
  halluckinationScore: number;
  verdict: string;
  generatedCode: string;
  evidence: Array<{
    kind: string;
    payload: Record<string, any>;
  }>;
  duration: number;
}

/**
 * Export run as JSON
 */
export function exportAsJSON(report: RunReport): void {
  const json = JSON.stringify(report, null, 2);
  downloadFile(json, `run-${report.runId}.json`, 'application/json');
}

/**
 * Export run as CSV (flattened)
 */
export function exportAsCSV(report: RunReport): void {
  const rows = [
    ['Field', 'Value'],
    ['Run ID', report.runId],
    ['Timestamp', report.timestamp],
    ['Language', report.language],
    ['Status', report.status],
    ['Hallucination Score', report.halluckinationScore.toFixed(2)],
    ['Verdict', report.verdict],
    ['Duration (ms)', report.duration.toString()],
    ['Prompt', report.prompt],
    ['Generated Code', report.generatedCode],
    [],
    ['Evidence Summary'],
    ...report.evidence.map((e) => [e.kind, JSON.stringify(e.payload)]),
  ];

  const csv = rows.map((row) => row.map((cell) => `"${cell.toString().replace(/"/g, '""')}"`).join(',')).join('\n');
  downloadFile(csv, `run-${report.runId}.csv`, 'text/csv');
}

/**
 * Export run as Markdown report
 */
export function exportAsMarkdown(report: RunReport): void {
  const md = `# DeHalu Verification Report

**Run ID:** ${report.runId}
**Timestamp:** ${report.timestamp}
**Duration:** ${report.duration}ms

## Summary

- **Language:** ${report.language}
- **Status:** ${report.status}
- **Hallucination Score:** ${(report.halluckinationScore * 100).toFixed(1)}%
- **Verdict:** ${report.verdict.toUpperCase()}

## Original Prompt

\`\`\`
${report.prompt}
\`\`\`

## Generated Code

\`\`\`${report.language.toLowerCase()}
${report.generatedCode}
\`\`\`

## Verification Evidence

${report.evidence
  .map(
    (e) => `### ${e.kind}

\`\`\`json
${JSON.stringify(e.payload, null, 2)}
\`\`\``
  )
  .join('\n\n')}

---

*Generated by DeHalu - AI Code Hallucination Detection System*
*${new Date().toISOString()}*
`;

  downloadFile(md, `run-${report.runId}.md`, 'text/markdown');
}

/**
 * Generate PDF report (requires PDF library)
 * For now, this generates a printable HTML that can be saved as PDF via browser
 */
export function generatePDFHTML(report: RunReport): string {
  const scorePercent = (report.halluckinationScore * 100).toFixed(0);
  const scoreColor = report.halluckinationScore > 0.7 ? '#EF4444' : 
                      report.halluckinationScore > 0.3 ? '#F59E0B' : 
                      '#10B981';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>DeHalu Report - ${report.runId}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #f9fafb;
    }
    .header {
      background: linear-gradient(135deg, #0051BA 0%, #004AA3 100%);
      color: white;
      padding: 40px;
      border-radius: 8px;
      margin-bottom: 40px;
    }
    .header h1 {
      margin: 0 0 10px 0;
      font-size: 28px;
    }
    .header p {
      margin: 5px 0;
      opacity: 0.95;
    }
    .score-box {
      display: inline-block;
      background: white;
      color: ${scoreColor};
      padding: 15px 25px;
      border-radius: 8px;
      font-weight: bold;
      font-size: 24px;
      margin: 20px 0;
    }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin: 30px 0;
    }
    .summary-card {
      background: white;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid #0051BA;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .summary-card label {
      display: block;
      font-size: 12px;
      color: #6b7280;
      font-weight: 600;
      margin-bottom: 5px;
      text-transform: uppercase;
    }
    .summary-card .value {
      font-size: 18px;
      font-weight: bold;
      color: #1f2937;
    }
    .section {
      background: white;
      padding: 30px;
      border-radius: 8px;
      margin-bottom: 30px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .section h2 {
      margin-top: 0;
      color: #0051BA;
      border-bottom: 2px solid #f0f0f0;
      padding-bottom: 10px;
    }
    code, pre {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
      font-size: 12px;
    }
    pre {
      padding: 15px;
      overflow-x: auto;
      border-left: 4px solid #0051BA;
    }
    .evidence-item {
      background: #f9fafb;
      padding: 15px;
      border-radius: 6px;
      margin-bottom: 15px;
      border-left: 3px solid #0051BA;
    }
    .verdict-badge {
      display: inline-block;
      padding: 8px 15px;
      border-radius: 20px;
      font-weight: bold;
      font-size: 14px;
    }
    .verdict-accept {
      background: #dcfce7;
      color: #166534;
    }
    .verdict-warn {
      background: #fef3c7;
      color: #b45309;
    }
    .verdict-repair {
      background: #e0e7ff;
      color: #3730a3;
    }
    .verdict-reject {
      background: #fee2e2;
      color: #991b1b;
    }
    .footer {
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
    @media print {
      body { background: white; }
      .header, .section { box-shadow: none; border: 1px solid #e5e7eb; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>DeHalu Verification Report</h1>
    <p><strong>Run ID:</strong> ${report.runId}</p>
    <p><strong>Generated:</strong> ${report.timestamp}</p>
    <div class="score-box">Hallucination Risk: ${scorePercent}%</div>
  </div>

  <div class="summary-grid">
    <div class="summary-card">
      <label>Language</label>
      <div class="value">${report.language}</div>
    </div>
    <div class="summary-card">
      <label>Status</label>
      <div class="value">${report.status}</div>
    </div>
    <div class="summary-card">
      <label>Duration</label>
      <div class="value">${report.duration}ms</div>
    </div>
    <div class="summary-card">
      <label>Verdict</label>
      <div class="verdict-badge verdict-${report.verdict}">${report.verdict.toUpperCase()}</div>
    </div>
  </div>

  <div class="section">
    <h2>Original Prompt</h2>
    <pre>${escapeHtml(report.prompt)}</pre>
  </div>

  <div class="section">
    <h2>Generated Code</h2>
    <pre><code>${escapeHtml(report.generatedCode)}</code></pre>
  </div>

  <div class="section">
    <h2>Verification Evidence</h2>
    ${report.evidence
      .map(
        (e) => `
      <div class="evidence-item">
        <h3>${e.kind}</h3>
        <pre><code>${escapeHtml(JSON.stringify(e.payload, null, 2))}</code></pre>
      </div>
    `
      )
      .join('')}
  </div>

  <div class="footer">
    <p>DeHalu - AI Code Hallucination Detection & Mitigation System</p>
    <p>Generated on ${new Date().toLocaleString()}</p>
  </div>
</body>
</html>
`;
}

/**
 * Trigger PDF export (browser's print-to-PDF)
 */
export function exportAsPDF(report: RunReport): void {
  const html = generatePDFHTML(report);
  const newWindow = window.open('', '_blank');
  if (newWindow) {
    newWindow.document.write(html);
    newWindow.document.close();
    newWindow.print();
  }
}

/**
 * Export multiple reports as ZIP (requires jszip library)
 */
export function exportMultipleReports(reports: RunReport[], format: 'json' | 'csv' | 'md'): void {
  const lines = reports.map((report) => {
    switch (format) {
      case 'json':
        return JSON.stringify(report, null, 2);
      case 'csv':
        return formatReportAsCSV(report);
      case 'md':
        return formatReportAsMarkdown(report);
    }
  });

  const content = lines.join('\n\n---\n\n');
  const filename = `dehalu-reports-${new Date().toISOString().split('T')[0]}.${format === 'md' ? 'md' : format}`;
  downloadFile(content, filename, format === 'json' ? 'application/json' : 'text/plain');
}

// Helper functions

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

function formatReportAsCSV(report: RunReport): string {
  const rows = [
    ['Field', 'Value'],
    ['Run ID', report.runId],
    ['Timestamp', report.timestamp],
    ['Language', report.language],
    ['Status', report.status],
    ['Hallucination Score', report.halluckinationScore.toFixed(2)],
    ['Verdict', report.verdict],
    ['Duration (ms)', report.duration.toString()],
  ];

  return rows.map((row) => row.map((cell) => `"${cell.toString().replace(/"/g, '""')}"`).join(',')).join('\n');
}

function formatReportAsMarkdown(report: RunReport): string {
  return `# ${report.runId}

**Timestamp:** ${report.timestamp}
**Language:** ${report.language}
**Verdict:** ${report.verdict}
**Score:** ${(report.halluckinationScore * 100).toFixed(1)}%

\`\`\`
${report.prompt}
\`\`\`

\`\`\`${report.language.toLowerCase()}
${report.generatedCode}
\`\`\`
`;
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
